repo: gardusig/clojure
jobs:
  - id: lint
    name: Repo lint
    target: lint
  - id: repo-hygiene
    name: Repo structure
    target: repo-hygiene
    needs: lint
    hygiene_policy:
      max_depth: 5
      allowed_root_dirs:
        - .github
        - .workflows
        - src
        - test
      allowed_root_files:
        - .gitignore
        - deps.edn
        - Dockerfile
        - LICENSE
        - Makefile
        - README.md
      allowed_extensions:
        - .clj
        - .edn
        - .md
        - .yaml
        - .yml
      allowed_filenames:
        - .gitignore
        - deps.edn
        - Dockerfile
        - LICENSE
        - Makefile
