repo: gardusig/sql
jobs:
  - id: lint
    name: Repo lint
    target: lint
  - id: repo-hygiene
    name: Repo structure
    target: repo-hygiene
    needs: lint
    hygiene_policy:
      max_depth: 4
      allowed_root_dirs:
        - .github
        - lib
        - examples
      allowed_root_files:
        - .gitignore
        - LICENSE
        - Makefile
        - README.md
      allowed_extensions:
        - .md
        - .sql
        - .yml
      allowed_filenames:
        - .gitignore
        - LICENSE
        - Makefile
