repo: gardusig/cli
dockerfile: docker/release.dockerfile
jobs:
  - id: pypi
    name: Publish to PyPI
    target: pypi
    build_args_from_ref: true
    secrets:
      PYPI_API_TOKEN: PYPI_API_TOKEN
  - id: runtime
    name: Lean Docker image
    target: runtime
    needs: pypi
    build_args_from_ref: true
